version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    executor: node/default
    steps:
      - node/install-packages:
          pkg-manager: npm
          
      - run: npm run test

  test_2:
    executor: node/default
    steps:
      - node/install-packages:
          pkg-manager: npm

workflows:
  main-workflow:
    jobs:
      - test
      - test_2
